import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import {demoFile} from '../assets/demo.mjs';
import * as W from '../assets/game-wire.mjs';

test('workspace controls edit, validate, recover, import, and undo list changes',async()=>{
  const dom=new JSDOM(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),{url:'http://localhost/',pretendToBeVisual:true});
  const w=dom.window;globalThis.window=w;globalThis.document=w.document;globalThis.confirm=()=>true;
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
  await import('../assets/workspace.mjs?dom-test');
  const $=id=>w.document.getElementById(id),change=input=>input.dispatchEvent(new w.Event('change',{bubbles:true}));
  $('demo').click();assert.equal($('workspace').hidden,false);assert.match($('file-name').textContent,/synthetic/);assert.equal($('export-file').disabled,true);
  const cards=()=>[...w.document.querySelectorAll('.variable-card')];
  const magazine=()=>cards().find(c=>c.querySelector('h2').textContent==='Magazine sizes');
  let value=magazine().querySelector('tbody input');value.value='1.5';change(value);assert.equal(value.getAttribute('aria-invalid'),'true');assert.match($('status').textContent,/Integer/);
  value.value='-12';change(value);assert.equal(value.hasAttribute('aria-invalid'),false);assert.match($('change-count').textContent,/1 modified/);
  magazine().querySelector('[aria-label="Duplicate row 1"]').click();assert.equal(magazine().querySelectorAll('tbody tr').length,6);
  $('undo').click();assert.equal(magazine().querySelectorAll('tbody tr').length,5);assert.equal(magazine().querySelector('tbody input').value,'-12');
  $('undo').click();assert.equal(magazine().querySelector('tbody input').value,'30');$('redo').click();assert.equal(magazine().querySelector('tbody input').value,'-12');
  [...magazine().querySelectorAll('button')].find(b=>b.textContent==='Paste / import').click();assert.equal($('bulk-dialog').open,true);
  $('bulk-text').value='[1, 2, "wrong"]';$('bulk-apply').click();assert.match($('bulk-error').textContent,/number/i);assert.equal($('bulk-dialog').open,true);
  $('bulk-text').value='[-2147483648, 0, 2147483647]';$('bulk-apply').click();assert.equal($('bulk-dialog').open,false);assert.equal(magazine().querySelectorAll('tbody tr').length,3);
  $('object-search').value='no matching record';$('object-search').dispatchEvent(new w.Event('input'));assert.match($('object-list').textContent,/No matching/);
  $('object-search').value='';$('object-search').dispatchEvent(new w.Event('input'));assert.equal($('object-list').querySelectorAll('button').length,1);
  // Open a real file object, exercising the asynchronous import path and format errors.
  const bytes=demoFile();Object.defineProperty($('file-input'),'files',{configurable:true,value:[{name:'fixture.gil',size:bytes.length,arrayBuffer:async()=>bytes.buffer}]});change($('file-input'));
  await new Promise(r=>setTimeout(r,70));assert.equal($('file-name').textContent,'fixture.gil');assert.equal($('export-file').disabled,false);
  Object.defineProperty($('file-input'),'files',{configurable:true,value:[{name:'broken.gil',size:24,arrayBuffer:async()=>new Uint8Array(24).buffer}]});change($('file-input'));
  await new Promise(r=>setTimeout(r,70));assert.match($('status').textContent,/magic/);assert.equal($('file-name').textContent,'fixture.gil');
  const uiRow=(name,order)=>W.concat([W.field(501,2,W.field(501,2,W.utf8(name))),W.field(502,2,W.EMPTY),W.field(505,0,order)]);
  const list=W.concat([W.field(501,2,uiRow('First',1)),W.field(501,2,uiRow('Second',2))]);
  const uiRecord=W.concat([W.field(501,0,100),W.field(505,2,W.concat([W.field(502,0,15),W.field(12,2,W.field(501,2,W.utf8('Test List')))])),W.field(505,2,W.concat([W.field(502,0,47),W.field(503,2,W.field(40,2,list))]))]);
  const uiFile=W.pack(W.field(9,2,W.field(502,2,uiRecord)));
  Object.defineProperty($('file-input'),'files',{configurable:true,value:[{name:'ui.gil',size:uiFile.length,arrayBuffer:async()=>uiFile.buffer}]});change($('file-input'));
  await new Promise(r=>setTimeout(r,70));assert.equal($('object-editor').querySelector('h1').textContent,'Test List');
  let name=w.document.querySelector('[aria-label="Row 1 name"]');name.value='<img src=x onerror=alert(1)>';change(name);assert.equal(w.document.querySelectorAll('img').length,0);
  w.document.querySelector('[aria-label="Duplicate row 1"]').click();assert.equal(w.document.querySelectorAll('.list-table tbody tr').length,3);
  w.document.querySelector('[aria-label="Move down row 1"]').click();assert.equal(w.document.querySelectorAll('.list-table tbody tr').length,3);
  $('undo').click();assert.equal(w.document.querySelectorAll('.list-table tbody tr').length,2);
  assert.equal(w.document.querySelector('[aria-label="Row 1 name"]').value,'<img src=x onerror=alert(1)>');
  dom.window.close();
});
